# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DISPATCH_PERMITTED_USER: ("shuntomi")

jobs:
  build:
    runs-on: ubuntu-latest
    # workflow_dispatchによる実行は特定のユーザーのみ許可する
#    if: >-
#      ${{
#        github.event_name == 'push' ||
#        ( github.event_name == 'workflow_dispatch' && contains(github.env.DISPATCH_PERMITTED_USER, github.actor) )
#      }}
    steps:
      - name: debug DISPATCH_PERMITTED_USER
        run: echo ${{ github.env.DISPATCH_PERMITTED_USER }}
      - name: debug DISPATCH_PERMITTED_USER
        run: echo ${{ contains(github.env.DISPATCH_PERMITTED_USER, github.actor) }}

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
